name: openrouter-eval

on:
  workflow_dispatch:

jobs:
  run-evaluator:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.10'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Run iterative evaluation with OpenRouter
        env:
          CONSTRUCTORTEST: ${{ secrets.CONSTRUCTORTEST }}
          OPENROUTER_BASE_URL: https://openrouter.ai/api/v1
          OPENROUTER_MODEL: openai/gpt-4o-mini
          LLM_PROVIDER: openrouter
        run: make run-iteratively USE_LLM=true
